repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
    - id: isort
      args: ['--check-only', '--diff']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
